const COLS=10, ROWS=20, CELL=30;
const canvas=document.getElementById("gameCanvas"), ctx=canvas.getContext("2d");
const nextCanvas=document.getElementById("nextCanvas"), nextCtx=nextCanvas.getContext("2d");
const scoreEl=document.getElementById("score"), linesEl=document.getElementById("lines"), levelEl=document.getElementById("level");
const overlay=document.getElementById("overlay"), overlayTitle=document.getElementById("overlayTitle"), overlayText=document.getElementById("overlayText");
const startBtn=document.getElementById("startBtn"), pauseBtn=document.getElementById("pauseBtn"), newGameBtn=document.getElementById("newGameBtn");
const leftBtn=document.getElementById("leftBtn"), rightBtn=document.getElementById("rightBtn"), rotateBtn=document.getElementById("rotateBtn"), downBtn=document.getElementById("downBtn"), dropBtn=document.getElementById("dropBtn");
const COLORS={I:"#22d3ee",O:"#fde047",T:"#c084fc",S:"#4ade80",Z:"#fb7185",J:"#60a5fa",L:"#fb923c"};
const SHAPES={I:[[0,0,0,0],[1,1,1,1],[0,0,0,0],[0,0,0,0]],O:[[1,1],[1,1]],T:[[0,1,0],[1,1,1],[0,0,0]],S:[[0,1,1],[1,1,0],[0,0,0]],Z:[[1,1,0],[0,1,1],[0,0,0]],J:[[1,0,0],[1,1,1],[0,0,0]],L:[[0,0,1],[1,1,1],[0,0,0]]};
let board,piece,nextPiece,score,lines,level,dropInterval,lastTime,dropCounter,running,paused,gameOver,particles;
function createBoard(){return Array.from({length:ROWS},()=>Array(COLS).fill(null));}
function cloneMatrix(m){return m.map(r=>[...r]);}
function randomPiece(){const keys=Object.keys(SHAPES),type=keys[Math.floor(Math.random()*keys.length)],matrix=cloneMatrix(SHAPES[type]);return{type,matrix,x:Math.floor(COLS/2)-Math.ceil(matrix[0].length/2),y:-1,color:COLORS[type]};}
function resetGame(){board=createBoard();piece=randomPiece();nextPiece=randomPiece();score=0;lines=0;level=1;dropInterval=900;lastTime=0;dropCounter=0;running=false;paused=false;gameOver=false;particles=[];updateHud();hideOverlay();draw();drawNext();}
function startGame(){if(gameOver)resetGame();running=true;paused=false;hideOverlay();lastTime=performance.now();requestAnimationFrame(update);}
function togglePause(){if(gameOver||!running)return;paused=!paused;if(paused)showOverlay("일시정지","계속하려면 일시정지를 다시 누르세요.");else{hideOverlay();lastTime=performance.now();requestAnimationFrame(update);}}
function update(time=0){if(!running||paused||gameOver)return;const delta=time-lastTime;lastTime=time;dropCounter+=delta;if(dropCounter>dropInterval){softDrop();dropCounter=0;}updateParticles(delta);draw();requestAnimationFrame(update);}
function updateHud(){scoreEl.textContent=score;linesEl.textContent=lines;levelEl.textContent=level;}
function showOverlay(t,x){overlayTitle.textContent=t;overlayText.textContent=x;overlay.classList.remove("hidden");}
function hideOverlay(){overlay.classList.add("hidden");}
function validMove(p,ox=0,oy=0,matrix=p.matrix){for(let y=0;y<matrix.length;y++){for(let x=0;x<matrix[y].length;x++){if(!matrix[y][x])continue;const nx=p.x+x+ox,ny=p.y+y+oy;if(nx<0||nx>=COLS||ny>=ROWS)return false;if(ny>=0&&board[ny][nx])return false;}}return true;}
function canControl(){return running&&!paused&&!gameOver;}
function move(dx){if(!canControl())return;if(validMove(piece,dx,0)){piece.x+=dx;draw();}}
function softDrop(){if(!canControl()&&!running)return false;if(validMove(piece,0,1)){piece.y+=1;return true;}lockPiece();return false;}
function hardDrop(){if(!canControl())return;let distance=0;while(validMove(piece,0,1)){piece.y+=1;distance++;}score+=distance*2;lockPiece();updateHud();draw();}
function rotate(){if(!canControl())return;const rotated=rotateMatrix(piece.matrix);for(const kick of [0,-1,1,-2,2]){if(validMove(piece,kick,0,rotated)){piece.matrix=rotated;piece.x+=kick;createSparklesForPiece(piece,8,"#f8fafc");draw();return;}}}
function rotateMatrix(matrix){const h=matrix.length,w=matrix[0].length,result=Array.from({length:w},()=>Array(h).fill(0));for(let y=0;y<h;y++)for(let x=0;x<w;x++)result[x][h-1-y]=matrix[y][x];return result;}
function lockPiece(){piece.matrix.forEach((row,y)=>row.forEach((v,x)=>{if(!v)return;const by=piece.y+y,bx=piece.x+x;if(by>=0)board[by][bx]=piece.color;}));createSparklesForPiece(piece,18,piece.color);clearLines();piece=nextPiece;nextPiece=randomPiece();drawNext();if(!validMove(piece,0,0))endGame();}
function clearLines(){const full=[];for(let y=ROWS-1;y>=0;y--)if(board[y].every(Boolean))full.push(y);if(!full.length)return;full.forEach(row=>{for(let x=0;x<COLS;x++)createBurst(x*CELL+CELL/2,row*CELL+CELL/2,8,board[row][x]||"#f8fafc");});board=board.filter((_,y)=>!full.includes(y));while(board.length<ROWS)board.unshift(Array(COLS).fill(null));const count=full.length;lines+=count;score+=[0,100,300,500,800][count]*level;level=Math.floor(lines/5)+1;dropInterval=Math.max(120,900-(level-1)*70);updateHud();}
function endGame(){gameOver=true;running=false;showOverlay("게임 종료",`점수 ${score}점! 새 게임을 눌러 다시 시작하세요.`);draw();}
function draw(){drawBackground();drawBoardBlocks();if(piece&&!gameOver)drawGhostPiece();if(piece&&!gameOver)drawPiece(piece);drawParticles();}
function drawBackground(){ctx.clearRect(0,0,canvas.width,canvas.height);const g=ctx.createLinearGradient(0,0,canvas.width,canvas.height);g.addColorStop(0,"#020617");g.addColorStop(.55,"#111827");g.addColorStop(1,"#1e1b4b");ctx.fillStyle=g;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle="rgba(148,163,184,.16)";ctx.lineWidth=1;for(let x=0;x<=COLS;x++){ctx.beginPath();ctx.moveTo(x*CELL,0);ctx.lineTo(x*CELL,ROWS*CELL);ctx.stroke();}for(let y=0;y<=ROWS;y++){ctx.beginPath();ctx.moveTo(0,y*CELL);ctx.lineTo(COLS*CELL,y*CELL);ctx.stroke();}}
function drawBoardBlocks(){board.forEach((row,y)=>row.forEach((color,x)=>{if(color)drawBlock(x,y,color);}));}
function drawPiece(p){p.matrix.forEach((row,y)=>row.forEach((v,x)=>{if(!v)return;const bx=p.x+x,by=p.y+y;if(by>=0)drawBlock(bx,by,p.color,true);}));}
function drawGhostPiece(){const ghost={...piece,x:piece.x,y:piece.y};while(validMove(ghost,0,1))ghost.y++;ghost.matrix.forEach((row,y)=>row.forEach((v,x)=>{if(!v)return;const bx=ghost.x+x,by=ghost.y+y;if(by<0)return;ctx.save();ctx.globalAlpha=.22;drawBlock(bx,by,"#f8fafc");ctx.restore();}));}
function drawBlock(x,y,color,active=false){const px=x*CELL,py=y*CELL,pad=2,r=7;ctx.save();ctx.shadowColor=color;ctx.shadowBlur=active?18:9;roundRect(px+pad,py+pad,CELL-pad*2,CELL-pad*2,r);const g=ctx.createLinearGradient(px,py,px+CELL,py+CELL);g.addColorStop(0,shadeColor(color,.36));g.addColorStop(.5,color);g.addColorStop(1,shadeColor(color,-.28));ctx.fillStyle=g;ctx.fill();ctx.lineWidth=2;ctx.strokeStyle="rgba(255,255,255,.58)";ctx.stroke();ctx.fillStyle="rgba(255,255,255,.26)";roundRect(px+7,py+6,CELL-14,5,5);ctx.fill();ctx.restore();}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath();}
function drawNext(){nextCtx.clearRect(0,0,nextCanvas.width,nextCanvas.height);nextCtx.fillStyle="rgba(15,23,42,.52)";nextCtx.fillRect(0,0,nextCanvas.width,nextCanvas.height);if(!nextPiece)return;const block=22,m=nextPiece.matrix,ox=(nextCanvas.width-m[0].length*block)/2,oy=(nextCanvas.height-m.length*block)/2;m.forEach((row,y)=>row.forEach((v,x)=>{if(!v)return;drawMiniBlock(nextCtx,ox+x*block,oy+y*block,block,nextPiece.color);}));}
function drawMiniBlock(c,x,y,s,color){c.save();c.shadowColor=color;c.shadowBlur=10;c.fillStyle=color;c.fillRect(x+2,y+2,s-4,s-4);c.strokeStyle="rgba(255,255,255,.65)";c.lineWidth=2;c.strokeRect(x+2,y+2,s-4,s-4);c.restore();}
function createSparklesForPiece(p,count,color){p.matrix.forEach((row,y)=>row.forEach((v,x)=>{if(!v)return;const bx=p.x+x,by=p.y+y;if(by>=0)createBurst(bx*CELL+CELL/2,by*CELL+CELL/2,count/4,color);}));}
function createBurst(x,y,count,color){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=.8+Math.random()*2.8;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:420+Math.random()*420,maxLife:840,color,size:2+Math.random()*3});}}
function updateParticles(delta){particles=particles.filter(p=>{p.life-=delta;p.x+=p.vx;p.y+=p.vy;p.vy+=.025;return p.life>0;});}
function drawParticles(){particles.forEach(p=>{ctx.save();ctx.globalAlpha=Math.max(0,p.life/p.maxLife);ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=12;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill();ctx.restore();});}
function shadeColor(hex,percent){const n=parseInt(hex.replace("#",""),16);let r=(n>>16)&255,g=(n>>8)&255,b=n&255;if(percent>=0){r=Math.round(r+(255-r)*percent);g=Math.round(g+(255-g)*percent);b=Math.round(b+(255-b)*percent);}else{r=Math.round(r*(1+percent));g=Math.round(g*(1+percent));b=Math.round(b*(1+percent));}return`rgb(${r},${g},${b})`;}
function bindHoldButton(button,action,repeatMs=90){let interval=null;const start=e=>{e.preventDefault();action();interval=setInterval(action,repeatMs);};const stop=()=>{if(interval)clearInterval(interval);interval=null;};button.addEventListener("pointerdown",start);button.addEventListener("pointerup",stop);button.addEventListener("pointercancel",stop);button.addEventListener("pointerleave",stop);}
document.addEventListener("keydown",e=>{if(e.key==="ArrowLeft"){e.preventDefault();move(-1);}else if(e.key==="ArrowRight"){e.preventDefault();move(1);}else if(e.key==="ArrowUp"){e.preventDefault();rotate();}else if(e.key==="ArrowDown"){e.preventDefault();if(softDrop()){score++;updateHud();draw();}}else if(e.code==="Space"){e.preventDefault();hardDrop();}else if(e.key.toLowerCase()==="p")togglePause();});
bindHoldButton(leftBtn,()=>move(-1),110);bindHoldButton(rightBtn,()=>move(1),110);bindHoldButton(downBtn,()=>{if(softDrop()){score++;updateHud();draw();}},70);rotateBtn.addEventListener("pointerdown",e=>{e.preventDefault();rotate();});dropBtn.addEventListener("pointerdown",e=>{e.preventDefault();hardDrop();});
startBtn.addEventListener("click",startGame);pauseBtn.addEventListener("click",togglePause);newGameBtn.addEventListener("click",()=>{resetGame();startGame();});
resetGame();showOverlay("준비 완료","게임 시작을 누르세요. 태블릿에서는 아래 버튼으로 조작합니다.");
